# Fly.io 배포 설정
app = "sentiment-analysis-platform"
primary_region = "nrt" # 도쿄 리전 (한국과 가까움)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# 볼륨 설정 (데이터베이스용)
[[mounts]]
  source = "data"
  destination = "/app/data"